// Code generated by Wire. DO NOT EDIT.

//go:generate wire
//+build !wireinject

package main

import (
	"go001/internal/biz"
	"go001/internal/data"
	"go001/internal/service"
)

// Injectors from rpc.go:

func InitRPCServer(redisAddr string) service.Server {
	dataOperator := data.NewRedis(redisAddr)
	bizHandler := biz.NewBiz(dataOperator)
	server := service.NewRPCServer(bizHandler)
	return server
}
